<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		Country::create(['id_minsal'=> 459 ,'code_deis'=>'004' ,'name'=>'Afganistán']);
		Country::create(['id_minsal'=> 460 ,'code_deis'=>'008' ,'name'=>'Albania']);
		Country::create(['id_minsal'=> 461 ,'code_deis'=>'276' ,'name'=>'Alemania']);
		Country::create(['id_minsal'=> 462 ,'code_deis'=>'012' ,'name'=>'Algeria']);
		Country::create(['id_minsal'=> 463 ,'code_deis'=>'020' ,'name'=>'Andorra']);
		Country::create(['id_minsal'=> 464 ,'code_deis'=>'024' ,'name'=>'Angola']);
		Country::create(['id_minsal'=> 465 ,'code_deis'=>'660' ,'name'=>'Anguila']);
		Country::create(['id_minsal'=> 466 ,'code_deis'=>'010' ,'name'=>'Antártida']);
		Country::create(['id_minsal'=> 467 ,'code_deis'=>'028' ,'name'=>'Antigua y Barbuda']);
		Country::create(['id_minsal'=> 468 ,'code_deis'=>'530' ,'name'=>'Antillas Neerlandesas']);
		Country::create(['id_minsal'=> 469 ,'code_deis'=>'682' ,'name'=>'Arabia Saudita']);
		Country::create(['id_minsal'=> 470 ,'code_deis'=>'032' ,'name'=>'Argentina']);
		Country::create(['id_minsal'=> 471 ,'code_deis'=>'051' ,'name'=>'Armenia']);
		Country::create(['id_minsal'=> 472 ,'code_deis'=>'533' ,'name'=>'Aruba']);
		Country::create(['id_minsal'=> 473 ,'code_deis'=>'036' ,'name'=>'Australia']);
		Country::create(['id_minsal'=> 474 ,'code_deis'=>'040' ,'name'=>'Austria']);
		Country::create(['id_minsal'=> 475 ,'code_deis'=>'031' ,'name'=>'Azerbayán']);
		Country::create(['id_minsal'=> 476 ,'code_deis'=>'056' ,'name'=>'Bélgica']);
		Country::create(['id_minsal'=> 477 ,'code_deis'=>'044' ,'name'=>'Bahamas']);
		Country::create(['id_minsal'=> 478 ,'code_deis'=>'048' ,'name'=>'Bahrein']);
		Country::create(['id_minsal'=> 479 ,'code_deis'=>'050' ,'name'=>'Bangladesh']);
		Country::create(['id_minsal'=> 480 ,'code_deis'=>'052' ,'name'=>'Barbados']);
		Country::create(['id_minsal'=> 481 ,'code_deis'=>'084' ,'name'=>'Belice']);
		Country::create(['id_minsal'=> 482 ,'code_deis'=>'204' ,'name'=>'Benín']);
		Country::create(['id_minsal'=> 483 ,'code_deis'=>'064' ,'name'=>'Bhután']);
		Country::create(['id_minsal'=> 484 ,'code_deis'=>'112' ,'name'=>'Bielorrusia']);
		Country::create(['id_minsal'=> 485 ,'code_deis'=>'104' ,'name'=>'Birmania']);
		Country::create(['id_minsal'=> 486 ,'code_deis'=>'068' ,'name'=>'Bolivia']);
		Country::create(['id_minsal'=> 487 ,'code_deis'=>'070' ,'name'=>'Bosnia y Herzegovina']);
		Country::create(['id_minsal'=> 488 ,'code_deis'=>'072' ,'name'=>'Botsuana']);
		Country::create(['id_minsal'=> 489 ,'code_deis'=>'076' ,'name'=>'Brasil']);
		Country::create(['id_minsal'=> 490 ,'code_deis'=>'096' ,'name'=>'Brunéi']);
		Country::create(['id_minsal'=> 491 ,'code_deis'=>'100' ,'name'=>'Bulgaria']);
		Country::create(['id_minsal'=> 492 ,'code_deis'=>'854' ,'name'=>'Burkina Faso']);
		Country::create(['id_minsal'=> 493 ,'code_deis'=>'108' ,'name'=>'Burundi']);
		Country::create(['id_minsal'=> 494 ,'code_deis'=>'132' ,'name'=>'Cabo Verde']);
		Country::create(['id_minsal'=> 495 ,'code_deis'=>'116' ,'name'=>'Camboya']);
		Country::create(['id_minsal'=> 496 ,'code_deis'=>'120' ,'name'=>'Camerún']);
		Country::create(['id_minsal'=> 497 ,'code_deis'=>'124' ,'name'=>'Canadá']);
		Country::create(['id_minsal'=> 498 ,'code_deis'=>'148' ,'name'=>'Chad']);
		Country::create(['id_minsal'=> 499 ,'code_deis'=>'152' ,'name'=>'Chile']);
		Country::create(['id_minsal'=> 500 ,'code_deis'=>'156' ,'name'=>'China']);
		Country::create(['id_minsal'=> 501 ,'code_deis'=>'196' ,'name'=>'Chipre']);
		Country::create(['id_minsal'=> 502 ,'code_deis'=>'336' ,'name'=>'Ciudad del Vaticano']);
		Country::create(['id_minsal'=> 503 ,'code_deis'=>'170' ,'name'=>'Colombia']);
		Country::create(['id_minsal'=> 504 ,'code_deis'=>'174' ,'name'=>'Comoras']);
		Country::create(['id_minsal'=> 505 ,'code_deis'=>'178' ,'name'=>'Congo']);
		Country::create(['id_minsal'=> 507 ,'code_deis'=>'408' ,'name'=>'Corea del Norte']);
		Country::create(['id_minsal'=> 508 ,'code_deis'=>'410' ,'name'=>'Corea del Sur']);
		Country::create(['id_minsal'=> 509 ,'code_deis'=>'384' ,'name'=>'Costa de Marfil']);
		Country::create(['id_minsal'=> 510 ,'code_deis'=>'188' ,'name'=>'Costa Rica']);
		Country::create(['id_minsal'=> 511 ,'code_deis'=>'191' ,'name'=>'Croacia']);
		Country::create(['id_minsal'=> 512 ,'code_deis'=>'192' ,'name'=>'Cuba']);
		Country::create(['id_minsal'=> 513 ,'code_deis'=>'208' ,'name'=>'Dinamarca']);
		Country::create(['id_minsal'=> 514 ,'code_deis'=>'212' ,'name'=>'Dominica']);
		Country::create(['id_minsal'=> 515 ,'code_deis'=>'218' ,'name'=>'Ecuador']);
		Country::create(['id_minsal'=> 516 ,'code_deis'=>'818' ,'name'=>'Egipto']);
		Country::create(['id_minsal'=> 517 ,'code_deis'=>'222' ,'name'=>'El Salvador']);
		Country::create(['id_minsal'=> 518 ,'code_deis'=>'784' ,'name'=>'Emiratos Árabes Unidos']);
		Country::create(['id_minsal'=> 519 ,'code_deis'=>'232' ,'name'=>'Eritrea']);
		Country::create(['id_minsal'=> 520 ,'code_deis'=>'703' ,'name'=>'Eslovaquia']);
		Country::create(['id_minsal'=> 521 ,'code_deis'=>'705' ,'name'=>'Eslovenia']);
		Country::create(['id_minsal'=> 522 ,'code_deis'=>'724' ,'name'=>'España']);
		Country::create(['id_minsal'=> 523 ,'code_deis'=>'840' ,'name'=>'Estados Unidos de América']);
		Country::create(['id_minsal'=> 524 ,'code_deis'=>'233' ,'name'=>'Estonia']);
		Country::create(['id_minsal'=> 525 ,'code_deis'=>'231' ,'name'=>'Etiopía']);
		Country::create(['id_minsal'=> 526 ,'code_deis'=>'608' ,'name'=>'Filipinas']);
		Country::create(['id_minsal'=> 527 ,'code_deis'=>'246' ,'name'=>'Finlandia']);
		Country::create(['id_minsal'=> 528 ,'code_deis'=>'242' ,'name'=>'Fiyi']);
		Country::create(['id_minsal'=> 529 ,'code_deis'=>'250' ,'name'=>'Francia']);
		Country::create(['id_minsal'=> 530 ,'code_deis'=>'266' ,'name'=>'Gabón']);
		Country::create(['id_minsal'=> 531 ,'code_deis'=>'270' ,'name'=>'Gambia']);
		Country::create(['id_minsal'=> 532 ,'code_deis'=>'268' ,'name'=>'Georgia']);
		Country::create(['id_minsal'=> 533 ,'code_deis'=>'288' ,'name'=>'Ghana']);
		Country::create(['id_minsal'=> 534 ,'code_deis'=>'292' ,'name'=>'Gibraltar']);
		Country::create(['id_minsal'=> 535 ,'code_deis'=>'308' ,'name'=>'Granada']);
		Country::create(['id_minsal'=> 536 ,'code_deis'=>'300' ,'name'=>'Grecia']);
		Country::create(['id_minsal'=> 537 ,'code_deis'=>'304' ,'name'=>'Groenlandia']);
		Country::create(['id_minsal'=> 538 ,'code_deis'=>'312' ,'name'=>'Guadalupe']);
		Country::create(['id_minsal'=> 539 ,'code_deis'=>'316' ,'name'=>'Guam']);
		Country::create(['id_minsal'=> 540 ,'code_deis'=>'320' ,'name'=>'Guatemala']);
		Country::create(['id_minsal'=> 541 ,'code_deis'=>'328' ,'name'=>'Guayana Francesa']);
		Country::create(['id_minsal'=> 542 ,'code_deis'=>'831' ,'name'=>'Guernsey']);
		Country::create(['id_minsal'=> 543 ,'code_deis'=>'324' ,'name'=>'Guinea']);
		Country::create(['id_minsal'=> 544 ,'code_deis'=>'226' ,'name'=>'Guinea Ecuatorial']);
		Country::create(['id_minsal'=> 545 ,'code_deis'=>'624' ,'name'=>'Guinea-Bissau']);
		Country::create(['id_minsal'=> 546 ,'code_deis'=>'328' ,'name'=>'Guyana']);
		Country::create(['id_minsal'=> 547 ,'code_deis'=>'332' ,'name'=>'Haití']);
		Country::create(['id_minsal'=> 548 ,'code_deis'=>'340' ,'name'=>'Honduras']);
		Country::create(['id_minsal'=> 549 ,'code_deis'=>'344' ,'name'=>'Hong kong']);
		Country::create(['id_minsal'=> 550 ,'code_deis'=>'348' ,'name'=>'Hungría']);
		Country::create(['id_minsal'=> 551 ,'code_deis'=>'356' ,'name'=>'India']);
		Country::create(['id_minsal'=> 552 ,'code_deis'=>'360' ,'name'=>'Indonesia']);
		Country::create(['id_minsal'=> 553 ,'code_deis'=>'364' ,'name'=>'Irán']);
		Country::create(['id_minsal'=> 554 ,'code_deis'=>'368' ,'name'=>'Irak']);
		Country::create(['id_minsal'=> 555 ,'code_deis'=>'372' ,'name'=>'Irlanda']);
		Country::create(['id_minsal'=> 556 ,'code_deis'=>'074' ,'name'=>'Isla Bouvet']);
		Country::create(['id_minsal'=> 557 ,'code_deis'=>'833' ,'name'=>'Isla de Man']);
		Country::create(['id_minsal'=> 558 ,'code_deis'=>'162' ,'name'=>'Isla de Navidad']);
		Country::create(['id_minsal'=> 559 ,'code_deis'=>'574' ,'name'=>'Isla Norfolk']);
		Country::create(['id_minsal'=> 560 ,'code_deis'=>'352' ,'name'=>'Islandia']);
		Country::create(['id_minsal'=> 561 ,'code_deis'=>'060' ,'name'=>'Islas Bermudas']);
		Country::create(['id_minsal'=> 562 ,'code_deis'=>'136' ,'name'=>'Islas Caimán']);
		Country::create(['id_minsal'=> 563 ,'code_deis'=>'166' ,'name'=>'Islas Cocos (Keeling)']);
		Country::create(['id_minsal'=> 564 ,'code_deis'=>'184' ,'name'=>'Islas Cook']);
		Country::create(['id_minsal'=> 565 ,'code_deis'=>'248' ,'name'=>'Islas de Åland']);
		Country::create(['id_minsal'=> 566 ,'code_deis'=>'234' ,'name'=>'Islas Feroe']);
		Country::create(['id_minsal'=> 567 ,'code_deis'=>'239' ,'name'=>'Islas Georgias del Sur y Sandwich del Sur']);
		Country::create(['id_minsal'=> 568 ,'code_deis'=>'334' ,'name'=>'Islas Heard y McDonald']);
		Country::create(['id_minsal'=> 569 ,'code_deis'=>'462' ,'name'=>'Islas Maldivas']);
		Country::create(['id_minsal'=> 571 ,'code_deis'=>NULL ,'name'=>'Islas Marianas del Norte']);
		Country::create(['id_minsal'=> 572 ,'code_deis'=>'584' ,'name'=>'Islas Marshall']);
		Country::create(['id_minsal'=> 573 ,'code_deis'=>'612' ,'name'=>'Islas Pitcairn']);
		Country::create(['id_minsal'=> 574 ,'code_deis'=>'090' ,'name'=>'Islas Salomón']);
		Country::create(['id_minsal'=> 575 ,'code_deis'=>'796' ,'name'=>'Islas Turcas y Caicos']);
		Country::create(['id_minsal'=> 576 ,'code_deis'=>NULL ,'name'=>'Islas Ultramarinas Menores de Estados Unidos']);
		Country::create(['id_minsal'=> 577 ,'code_deis'=>'092' ,'name'=>'Islas Vírgenes Británicas']);
		Country::create(['id_minsal'=> 578 ,'code_deis'=>'850' ,'name'=>'Islas Vírgenes de los Estados Unidos']);
		Country::create(['id_minsal'=> 579 ,'code_deis'=>'376' ,'name'=>'Israel']);
		Country::create(['id_minsal'=> 580 ,'code_deis'=>'380' ,'name'=>'Italia']);
		Country::create(['id_minsal'=> 581 ,'code_deis'=>'388' ,'name'=>'Jamaica']);
		Country::create(['id_minsal'=> 582 ,'code_deis'=>'392' ,'name'=>'Japón']);
		Country::create(['id_minsal'=> 583 ,'code_deis'=>'832' ,'name'=>'Jersey']);
		Country::create(['id_minsal'=> 584 ,'code_deis'=>'400' ,'name'=>'Jordania']);
		Country::create(['id_minsal'=> 585 ,'code_deis'=>'398' ,'name'=>'Kazajistán']);
		Country::create(['id_minsal'=> 586 ,'code_deis'=>'404' ,'name'=>'Kenia']);
		Country::create(['id_minsal'=> 587 ,'code_deis'=>'417' ,'name'=>'Kirgizstán']);
		Country::create(['id_minsal'=> 588 ,'code_deis'=>'296' ,'name'=>'Kiribati']);
		Country::create(['id_minsal'=> 589 ,'code_deis'=>'414' ,'name'=>'Kuwait']);
		Country::create(['id_minsal'=> 590 ,'code_deis'=>'422' ,'name'=>'Líbano']);
		Country::create(['id_minsal'=> 591 ,'code_deis'=>'418' ,'name'=>'Laos']);
		Country::create(['id_minsal'=> 592 ,'code_deis'=>'426' ,'name'=>'Lesoto']);
		Country::create(['id_minsal'=> 593 ,'code_deis'=>'428' ,'name'=>'Letonia']);
		Country::create(['id_minsal'=> 594 ,'code_deis'=>'430' ,'name'=>'Liberia']);
		Country::create(['id_minsal'=> 595 ,'code_deis'=>'434' ,'name'=>'Libia']);
		Country::create(['id_minsal'=> 596 ,'code_deis'=>'438' ,'name'=>'Liechtenstein']);
		Country::create(['id_minsal'=> 597 ,'code_deis'=>'440' ,'name'=>'Lituania']);
		Country::create(['id_minsal'=> 598 ,'code_deis'=>'442' ,'name'=>'Luxemburgo']);
		Country::create(['id_minsal'=> 599 ,'code_deis'=>'484' ,'name'=>'México']);
		Country::create(['id_minsal'=> 600 ,'code_deis'=>'492' ,'name'=>'Mónaco']);
		Country::create(['id_minsal'=> 601 ,'code_deis'=>'446' ,'name'=>'Macao']);
		Country::create(['id_minsal'=> 602 ,'code_deis'=>'807' ,'name'=>'Macedônia']);
		Country::create(['id_minsal'=> 603 ,'code_deis'=>'450' ,'name'=>'Madagascar']);
		Country::create(['id_minsal'=> 604 ,'code_deis'=>'458' ,'name'=>'Malasia']);
		Country::create(['id_minsal'=> 605 ,'code_deis'=>'454' ,'name'=>'Malawi']);
		Country::create(['id_minsal'=> 606 ,'code_deis'=>'466' ,'name'=>'Mali']);
		Country::create(['id_minsal'=> 607 ,'code_deis'=>'470' ,'name'=>'Malta']);
		Country::create(['id_minsal'=> 608 ,'code_deis'=>'504' ,'name'=>'Marruecos']);
		Country::create(['id_minsal'=> 609 ,'code_deis'=>'474' ,'name'=>'Martinica']);
		Country::create(['id_minsal'=> 610 ,'code_deis'=>'480' ,'name'=>'Mauricio']);
		Country::create(['id_minsal'=> 611 ,'code_deis'=>'478' ,'name'=>'Mauritania']);
		Country::create(['id_minsal'=> 612 ,'code_deis'=>'175' ,'name'=>'Mayotte']);
		Country::create(['id_minsal'=> 613 ,'code_deis'=>'583' ,'name'=>'Micronesia']);
		Country::create(['id_minsal'=> 614 ,'code_deis'=>'498' ,'name'=>'Moldavia']);
		Country::create(['id_minsal'=> 615 ,'code_deis'=>'496' ,'name'=>'Mongolia']);
		Country::create(['id_minsal'=> 616 ,'code_deis'=>'499' ,'name'=>'Montenegro']);
		Country::create(['id_minsal'=> 617 ,'code_deis'=>'500' ,'name'=>'Montserrat']);
		Country::create(['id_minsal'=> 618 ,'code_deis'=>'508' ,'name'=>'Mozambique']);
		Country::create(['id_minsal'=> 619 ,'code_deis'=>'516' ,'name'=>'Namibia']);
		Country::create(['id_minsal'=> 620 ,'code_deis'=>'520' ,'name'=>'Nauru']);
		Country::create(['id_minsal'=> 621 ,'code_deis'=>'524' ,'name'=>'Nepal']);
		Country::create(['id_minsal'=> 622 ,'code_deis'=>'558' ,'name'=>'Nicaragua']);
		Country::create(['id_minsal'=> 623 ,'code_deis'=>'562' ,'name'=>'Niger']);
		Country::create(['id_minsal'=> 624 ,'code_deis'=>'566' ,'name'=>'Nigeria']);
		Country::create(['id_minsal'=> 625 ,'code_deis'=>'570' ,'name'=>'Niue']);
		Country::create(['id_minsal'=> 626 ,'code_deis'=>'578' ,'name'=>'Noruega']);
		Country::create(['id_minsal'=> 627 ,'code_deis'=>'540' ,'name'=>'Nueva Caledonia']);
		Country::create(['id_minsal'=> 628 ,'code_deis'=>'554' ,'name'=>'Nueva Zelanda']);
		Country::create(['id_minsal'=> 629 ,'code_deis'=>'512' ,'name'=>'Omán']);
		Country::create(['id_minsal'=> 630 ,'code_deis'=>'528' ,'name'=>'Países Bajos']);
		Country::create(['id_minsal'=> 631 ,'code_deis'=>'586' ,'name'=>'Pakistán']);
		Country::create(['id_minsal'=> 632 ,'code_deis'=>'585' ,'name'=>'Palau']);
		Country::create(['id_minsal'=> 633 ,'code_deis'=>'275' ,'name'=>'Palestina']);
		Country::create(['id_minsal'=> 634 ,'code_deis'=>'591' ,'name'=>'Panamá']);
		Country::create(['id_minsal'=> 635 ,'code_deis'=>'598' ,'name'=>'Papúa Nueva Guinea']);
		Country::create(['id_minsal'=> 636 ,'code_deis'=>'600' ,'name'=>'Paraguay']);
		Country::create(['id_minsal'=> 637 ,'code_deis'=>'604' ,'name'=>'Perú']);
		Country::create(['id_minsal'=> 638 ,'code_deis'=>'258' ,'name'=>'Polinesia Francesa']);
		Country::create(['id_minsal'=> 639 ,'code_deis'=>'616' ,'name'=>'Polonia']);
		Country::create(['id_minsal'=> 640 ,'code_deis'=>'620' ,'name'=>'Portugal']);
		Country::create(['id_minsal'=> 641 ,'code_deis'=>'630' ,'name'=>'Puerto Rico']);
		Country::create(['id_minsal'=> 642 ,'code_deis'=>'634' ,'name'=>'Qatar']);
		Country::create(['id_minsal'=> 643 ,'code_deis'=>'826' ,'name'=>'Reino Unido']);
		Country::create(['id_minsal'=> 644 ,'code_deis'=>'140' ,'name'=>'República Centroafricana']);
		Country::create(['id_minsal'=> 645 ,'code_deis'=>'203' ,'name'=>'República Checa']);
		Country::create(['id_minsal'=> 646 ,'code_deis'=>'214' ,'name'=>'República Dominicana']);
		Country::create(['id_minsal'=> 647 ,'code_deis'=>'638' ,'name'=>'Reunión']);
		Country::create(['id_minsal'=> 648 ,'code_deis'=>'646' ,'name'=>'Ruanda']);
		Country::create(['id_minsal'=> 649 ,'code_deis'=>'642' ,'name'=>'Rumanía']);
		Country::create(['id_minsal'=> 650 ,'code_deis'=>'643' ,'name'=>'Rusia']);
		Country::create(['id_minsal'=> 651 ,'code_deis'=>'732' ,'name'=>'Sahara Occidental']);
		Country::create(['id_minsal'=> 652 ,'code_deis'=>'882' ,'name'=>'Samoa']);
		Country::create(['id_minsal'=> 653 ,'code_deis'=>'016' ,'name'=>'Samoa Americana']);
		Country::create(['id_minsal'=> 654 ,'code_deis'=>'652' ,'name'=>'San Bartolomé']);
		Country::create(['id_minsal'=> 655 ,'code_deis'=>'659' ,'name'=>'San Cristóbal y Nieves']);
		Country::create(['id_minsal'=> 656 ,'code_deis'=>'674' ,'name'=>'San Marino']);
		Country::create(['id_minsal'=> 657 ,'code_deis'=>NULL ,'name'=>'San Martín (Francia)']);
		Country::create(['id_minsal'=> 658 ,'code_deis'=>'666' ,'name'=>'San Pedro y Miquelón']);
		Country::create(['id_minsal'=> 659 ,'code_deis'=>'670' ,'name'=>'San Vicente y las Granadinas']);
		Country::create(['id_minsal'=> 660 ,'code_deis'=>'654' ,'name'=>'Santa Elena']);
		Country::create(['id_minsal'=> 661 ,'code_deis'=>'662' ,'name'=>'Santa Lucía']);
		Country::create(['id_minsal'=> 662 ,'code_deis'=>'678' ,'name'=>'Santo Tomé y Príncipe']);
		Country::create(['id_minsal'=> 663 ,'code_deis'=>'686' ,'name'=>'Senegal']);
		Country::create(['id_minsal'=> 664 ,'code_deis'=>'688' ,'name'=>'Serbia']);
		Country::create(['id_minsal'=> 665 ,'code_deis'=>'690' ,'name'=>'Seychelles']);
		Country::create(['id_minsal'=> 666 ,'code_deis'=>'694' ,'name'=>'Sierra Leona']);
		Country::create(['id_minsal'=> 667 ,'code_deis'=>'702' ,'name'=>'Singapur']);
		Country::create(['id_minsal'=> 668 ,'code_deis'=>'760' ,'name'=>'Siria']);
		Country::create(['id_minsal'=> 669 ,'code_deis'=>'706' ,'name'=>'Somalia']);
		Country::create(['id_minsal'=> 670 ,'code_deis'=>'144' ,'name'=>'Sri lanka']);
		Country::create(['id_minsal'=> 671 ,'code_deis'=>'710' ,'name'=>'Sudáfrica']);
		Country::create(['id_minsal'=> 672 ,'code_deis'=>'736' ,'name'=>'Sudán']);
		Country::create(['id_minsal'=> 673 ,'code_deis'=>'752' ,'name'=>'Suecia']);
		Country::create(['id_minsal'=> 674 ,'code_deis'=>'756' ,'name'=>'Suiza']);
		Country::create(['id_minsal'=> 675 ,'code_deis'=>'740' ,'name'=>'Surinám']);
		Country::create(['id_minsal'=> 676 ,'code_deis'=>'744' ,'name'=>'Svalbard y Jan Mayen']);
		Country::create(['id_minsal'=> 677 ,'code_deis'=>'748' ,'name'=>'Swazilandia']);
		Country::create(['id_minsal'=> 678 ,'code_deis'=>'762' ,'name'=>'Tadjikistán']);
		Country::create(['id_minsal'=> 679 ,'code_deis'=>'764' ,'name'=>'Tailandia']);
		Country::create(['id_minsal'=> 680 ,'code_deis'=>'158' ,'name'=>'Taiwán']);
		Country::create(['id_minsal'=> 681 ,'code_deis'=>'834' ,'name'=>'Tanzania']);
		Country::create(['id_minsal'=> 682 ,'code_deis'=>'086' ,'name'=>'Territorio Británico del Océano Índico']);
		Country::create(['id_minsal'=> 683 ,'code_deis'=>'260' ,'name'=>'Territorios Australes y Antárticas Franceses']);
		Country::create(['id_minsal'=> 684 ,'code_deis'=>'626' ,'name'=>'Timor Oriental']);
		Country::create(['id_minsal'=> 685 ,'code_deis'=>'768' ,'name'=>'Togo']);
		Country::create(['id_minsal'=> 686 ,'code_deis'=>'772' ,'name'=>'Tokelau']);
		Country::create(['id_minsal'=> 687 ,'code_deis'=>'776' ,'name'=>'Tonga']);
		Country::create(['id_minsal'=> 688 ,'code_deis'=>'780' ,'name'=>'Trinidad y Tobago']);
		Country::create(['id_minsal'=> 689 ,'code_deis'=>'788' ,'name'=>'Tunez']);
		Country::create(['id_minsal'=> 690 ,'code_deis'=>'795' ,'name'=>'Turkmenistán']);
		Country::create(['id_minsal'=> 691 ,'code_deis'=>'792' ,'name'=>'Turquía']);
		Country::create(['id_minsal'=> 692 ,'code_deis'=>'798' ,'name'=>'Tuvalu']);
		Country::create(['id_minsal'=> 693 ,'code_deis'=>'804' ,'name'=>'Ucrania']);
		Country::create(['id_minsal'=> 694 ,'code_deis'=>'800' ,'name'=>'Uganda']);
		Country::create(['id_minsal'=> 695 ,'code_deis'=>'858' ,'name'=>'Uruguay']);
		Country::create(['id_minsal'=> 696 ,'code_deis'=>'860' ,'name'=>'Uzbekistán']);
		Country::create(['id_minsal'=> 697 ,'code_deis'=>'548' ,'name'=>'Vanuatu']);
		Country::create(['id_minsal'=> 698 ,'code_deis'=>'862' ,'name'=>'Venezuela']);
		Country::create(['id_minsal'=> 699 ,'code_deis'=>'704' ,'name'=>'Vietnam']);
		Country::create(['id_minsal'=> 700 ,'code_deis'=>'876' ,'name'=>'Wallis y Futuna']);
		Country::create(['id_minsal'=> 701 ,'code_deis'=>'887' ,'name'=>'Yemen']);
		Country::create(['id_minsal'=> 702 ,'code_deis'=>'262' ,'name'=>'Yibuti']);
		Country::create(['id_minsal'=> 703 ,'code_deis'=>NULL ,'name'=>'Zambia']);
		Country::create(['id_minsal'=> 704 ,'code_deis'=>NULL ,'name'=>'Zimbabue']);

		/*
		Country::create(['iso_cod' => 'AFG', 'name' => 'Afganistán']);
		Country::create(['iso_cod' => 'ALB', 'name' => 'Albania']);
		Country::create(['iso_cod' => 'DEU', 'name' => 'Alemania']);
		Country::create(['iso_cod' => 'DZA', 'name' => 'Algeria']);
		Country::create(['iso_cod' => 'AND', 'name' => 'Andorra']);
		Country::create(['iso_cod' => 'AGO', 'name' => 'Angola']);
		Country::create(['iso_cod' => 'AIA', 'name' => 'Anguila']);
		Country::create(['iso_cod' => 'ATA', 'name' => 'Antártida']);
		Country::create(['iso_cod' => 'ATG', 'name' => 'Antigua y Barbuda']);
		Country::create(['iso_cod' => 'ANT', 'name' => 'Antillas Neerlandesas']);
		Country::create(['iso_cod' => 'SAU', 'name' => 'Arabia Saudita']);
		Country::create(['iso_cod' => 'DZA', 'name' => 'Argelia']);
		Country::create(['iso_cod' => 'ARG', 'name' => 'Argentina']);
		Country::create(['iso_cod' => 'ARM', 'name' => 'Armenia']);
		Country::create(['iso_cod' => 'ABW', 'name' => 'Aruba']);
		Country::create(['iso_cod' => 'AUS', 'name' => 'Australia']);
		Country::create(['iso_cod' => 'AUT', 'name' => 'Austria']);
		Country::create(['iso_cod' => 'AZE', 'name' => 'Azerbayán']);
		Country::create(['iso_cod' => 'BEL', 'name' => 'Bélgica']);
		Country::create(['iso_cod' => 'BHS', 'name' => 'Bahamas']);
		Country::create(['iso_cod' => 'BHR', 'name' => 'Bahrein']);
		Country::create(['iso_cod' => 'BGD', 'name' => 'Bangladesh']);
		Country::create(['iso_cod' => 'BRB', 'name' => 'Barbados']);
		Country::create(['iso_cod' => 'BLZ', 'name' => 'Belice']);
		Country::create(['iso_cod' => 'BEN', 'name' => 'Benín']);
		Country::create(['iso_cod' => 'BTN', 'name' => 'Bután']);
		Country::create(['iso_cod' => 'BLR', 'name' => 'Bielorrusia']);
		Country::create(['iso_cod' => 'BOL', 'name' => 'Bolivia']);
		Country::create(['iso_cod' => 'BIH', 'name' => 'Bosnia y Herzegovina']);
		Country::create(['iso_cod' => 'BWA', 'name' => 'Botsuana']);
		Country::create(['iso_cod' => 'BRA', 'name' => 'Brasil']);
		Country::create(['iso_cod' => 'BRN', 'name' => 'Brunéi']);
		Country::create(['iso_cod' => 'BGR', 'name' => 'Bulgaria']);
		Country::create(['iso_cod' => 'BFA', 'name' => 'Burkina Faso']);
		Country::create(['iso_cod' => 'BDI', 'name' => 'Burundi']);
		Country::create(['iso_cod' => 'CPV', 'name' => 'Cabo Verde']);
		Country::create(['iso_cod' => 'KHM', 'name' => 'Camboya']);
		Country::create(['iso_cod' => 'CMR', 'name' => 'Camerún']);
		Country::create(['iso_cod' => 'CAN', 'name' => 'Canadá']);
		Country::create(['iso_cod' => 'TCD', 'name' => 'Chad']);
		Country::create(['iso_cod' => 'CHL', 'name' => 'Chile']);
		Country::create(['iso_cod' => 'CHN', 'name' => 'China']);
		Country::create(['iso_cod' => 'CYP', 'name' => 'Chipre']);
		Country::create(['iso_cod' => 'VAT', 'name' => 'Ciudad del Vaticano']);
		Country::create(['iso_cod' => 'COL', 'name' => 'Colombia']);
		Country::create(['iso_cod' => 'COM', 'name' => 'Comoras']);
		Country::create(['iso_cod' => 'COG', 'name' => 'Congo']);
		Country::create(['iso_cod' => 'PRK', 'name' => 'Corea del Norte']);
		Country::create(['iso_cod' => 'KOR', 'name' => 'Corea del Sur']);
		Country::create(['iso_cod' => 'CIV', 'name' => 'Costa de Marfil']);
		Country::create(['iso_cod' => 'CRI', 'name' => 'Costa Rica']);
		Country::create(['iso_cod' => 'HRV', 'name' => 'Croacia']);
		Country::create(['iso_cod' => 'CUB', 'name' => 'Cuba']);
		Country::create(['iso_cod' => 'DNK', 'name' => 'Dinamarca']);
		Country::create(['iso_cod' => 'DMA', 'name' => 'Dominica']);
		Country::create(['iso_cod' => 'ECU', 'name' => 'Ecuador']);
		Country::create(['iso_cod' => 'EGY', 'name' => 'Egipto']);
		Country::create(['iso_cod' => 'SLV', 'name' => 'El Salvador']);
		Country::create(['iso_cod' => 'ARE', 'name' => 'Emiratos Árabes Unidos']);
		Country::create(['iso_cod' => 'ERI', 'name' => 'Eritrea']);
		Country::create(['iso_cod' => 'SVK', 'name' => 'Eslovaquia']);
		Country::create(['iso_cod' => 'SVN', 'name' => 'Eslovenia']);
		Country::create(['iso_cod' => 'ESP', 'name' => 'España']);
		Country::create(['iso_cod' => 'USA', 'name' => 'Estados Unidos de América']);
		Country::create(['iso_cod' => 'EST', 'name' => 'Estonia']);
		Country::create(['iso_cod' => 'ETH', 'name' => 'Etiopía']);
		Country::create(['iso_cod' => 'PHL', 'name' => 'Filipinas']);
		Country::create(['iso_cod' => 'FIN', 'name' => 'Finlandia']);
		Country::create(['iso_cod' => 'FJI', 'name' => 'Fiyi']);
		Country::create(['iso_cod' => 'FRA', 'name' => 'Francia']);
		Country::create(['iso_cod' => 'GAB', 'name' => 'Gabón']);
		Country::create(['iso_cod' => 'GMB', 'name' => 'Gambia']);
		Country::create(['iso_cod' => 'GEO', 'name' => 'Georgia']);
		Country::create(['iso_cod' => 'GHA', 'name' => 'Ghana']);
		Country::create(['iso_cod' => 'GIB', 'name' => 'Gibraltar']);
		Country::create(['iso_cod' => 'GRD', 'name' => 'Granada']);
		Country::create(['iso_cod' => 'GRC', 'name' => 'Grecia']);
		Country::create(['iso_cod' => 'GRL', 'name' => 'Groenlandia']);
		Country::create(['iso_cod' => 'GLP', 'name' => 'Guadalupe']);
		Country::create(['iso_cod' => 'GUM', 'name' => 'Guam']);
		Country::create(['iso_cod' => 'GTM', 'name' => 'Guatemala']);
		Country::create(['iso_cod' => 'GUF', 'name' => 'Guayana Francesa']);
		Country::create(['iso_cod' => 'GGY', 'name' => 'Guernsey']);
		Country::create(['iso_cod' => 'GIN', 'name' => 'Guinea']);
		Country::create(['iso_cod' => 'GNQ', 'name' => 'Guinea Ecuatorial']);
		Country::create(['iso_cod' => 'GNB', 'name' => 'Guinea-Bissau']);
		Country::create(['iso_cod' => 'GUY', 'name' => 'Guyana']);
		Country::create(['iso_cod' => 'HTI', 'name' => 'Haití']);
		Country::create(['iso_cod' => 'HND', 'name' => 'Honduras']);
		Country::create(['iso_cod' => 'HKG', 'name' => 'Hong kong']);
		Country::create(['iso_cod' => 'HUN', 'name' => 'Hungría']);
		Country::create(['iso_cod' => 'IND', 'name' => 'India']);
		Country::create(['iso_cod' => 'IDN', 'name' => 'Indonesia']);
		Country::create(['iso_cod' => 'IRN', 'name' => 'Irán']);
		Country::create(['iso_cod' => 'IRQ', 'name' => 'Irak']);
		Country::create(['iso_cod' => 'IRL', 'name' => 'Irlanda']);
		Country::create(['iso_cod' => 'BVT', 'name' => 'Isla Bouvet']);
		Country::create(['iso_cod' => 'IMN', 'name' => 'Isla de Man']);
		Country::create(['iso_cod' => 'CXR', 'name' => 'Isla de Navidad']);
		Country::create(['iso_cod' => 'NFK', 'name' => 'Isla Norfolk']);
		Country::create(['iso_cod' => 'ISL', 'name' => 'Islandia']);
		Country::create(['iso_cod' => 'BMU', 'name' => 'Islas Bermudas']);
		Country::create(['iso_cod' => 'CYM', 'name' => 'Islas Caimán']);
		Country::create(['iso_cod' => 'CCK', 'name' => 'Islas Cocos (Keeling)']);
		Country::create(['iso_cod' => 'COK', 'name' => 'Islas Cook']);
		Country::create(['iso_cod' => 'ALA', 'name' => 'Islas de Åland']);
		Country::create(['iso_cod' => 'FRO', 'name' => 'Islas Faroe']);
		Country::create(['iso_cod' => 'SGS', 'name' => 'Islas Georgias del Sur y Sandwich del Sur']);
		Country::create(['iso_cod' => 'HMD', 'name' => 'Islas Heard y McDonald']);
		Country::create(['iso_cod' => 'FLK', 'name' => 'Islas Maldivas']);
		Country::create(['iso_cod' => 'MNP', 'name' => 'Islas Marianas del Norte']);
		Country::create(['iso_cod' => 'MHL', 'name' => 'Islas Marshall']);
		Country::create(['iso_cod' => 'PCN', 'name' => 'Islas Pitcairn']);
		Country::create(['iso_cod' => 'SLB', 'name' => 'Islas Salomón']);
		Country::create(['iso_cod' => 'TCA', 'name' => 'Islas Turcas y Caicos']);
		Country::create(['iso_cod' => 'UMI', 'name' => 'Islas Ultramarinas Menores de Estados Unidos']);
		Country::create(['iso_cod' => 'VGB', 'name' => 'Islas Vírgenes Británicas']);
		Country::create(['iso_cod' => 'VIR', 'name' => 'Islas Vírgenes de los Estados Unidos']);
		Country::create(['iso_cod' => 'ISR', 'name' => 'Israel']);
		Country::create(['iso_cod' => 'ITA', 'name' => 'Italia']);
		Country::create(['iso_cod' => 'JAM', 'name' => 'Jamaica']);
		Country::create(['iso_cod' => 'JPN', 'name' => 'Japón']);
		Country::create(['iso_cod' => 'JEY', 'name' => 'Jersey']);
		Country::create(['iso_cod' => 'JOR', 'name' => 'Jordania']);
		Country::create(['iso_cod' => 'KAZ', 'name' => 'Kazajistán']);
		Country::create(['iso_cod' => 'KEN', 'name' => 'Kenia']);
		Country::create(['iso_cod' => 'KGZ', 'name' => 'Kirgizstán']);
		Country::create(['iso_cod' => 'KIR', 'name' => 'Kiribati']);
		Country::create(['iso_cod' => 'KWT', 'name' => 'Kuwait']);
		Country::create(['iso_cod' => 'LBN', 'name' => 'Líbano']);
		Country::create(['iso_cod' => 'LAO', 'name' => 'Laos']);
		Country::create(['iso_cod' => 'LSO', 'name' => 'Lesoto']);
		Country::create(['iso_cod' => 'LVA', 'name' => 'Letonia']);
		Country::create(['iso_cod' => 'LBR', 'name' => 'Liberia']);
		Country::create(['iso_cod' => 'LBY', 'name' => 'Libia']);
		Country::create(['iso_cod' => 'LIE', 'name' => 'Liechtenstein']);
		Country::create(['iso_cod' => 'LTU', 'name' => 'Lituania']);
		Country::create(['iso_cod' => 'LUX', 'name' => 'Luxemburgo']);
		Country::create(['iso_cod' => 'MEX', 'name' => 'México']);
		Country::create(['iso_cod' => 'MCO', 'name' => 'Mónaco']);
		Country::create(['iso_cod' => 'MAC', 'name' => 'Macao']);
		Country::create(['iso_cod' => 'MKD', 'name' => 'Macedônia']);
		Country::create(['iso_cod' => 'MDG', 'name' => 'Madagascar']);
		Country::create(['iso_cod' => 'MYS', 'name' => 'Malasia']);
		Country::create(['iso_cod' => 'MWI', 'name' => 'Malawi']);
		Country::create(['iso_cod' => 'MLI', 'name' => 'Mali']);
		Country::create(['iso_cod' => 'MLT', 'name' => 'Malta']);
		Country::create(['iso_cod' => 'MAR', 'name' => 'Marruecos']);
		Country::create(['iso_cod' => 'MTQ', 'name' => 'Martinica']);
		Country::create(['iso_cod' => 'MUS', 'name' => 'Mauricio']);
		Country::create(['iso_cod' => 'MRT', 'name' => 'Mauritania']);
		Country::create(['iso_cod' => 'MYT', 'name' => 'Mayotte']);
		Country::create(['iso_cod' => 'FSM', 'name' => 'Micronesia']);
		Country::create(['iso_cod' => 'MDA', 'name' => 'Moldavia']);
		Country::create(['iso_cod' => 'MNG', 'name' => 'Mongolia']);
		Country::create(['iso_cod' => 'MNE', 'name' => 'Montenegro']);
		Country::create(['iso_cod' => 'MSR', 'name' => 'Montserrat']);
		Country::create(['iso_cod' => 'MOZ', 'name' => 'Mozambique']);
		Country::create(['iso_cod' => 'MMR', 'name' => 'Myanmar']);
		Country::create(['iso_cod' => 'NAM', 'name' => 'Namibia']);
		Country::create(['iso_cod' => 'NRU', 'name' => 'Nauru']);
		Country::create(['iso_cod' => 'NPL', 'name' => 'Nepal']);
		Country::create(['iso_cod' => 'NIC', 'name' => 'Nicaragua']);
		Country::create(['iso_cod' => 'NER', 'name' => 'Niger']);
		Country::create(['iso_cod' => 'NGA', 'name' => 'Nigeria']);
		Country::create(['iso_cod' => 'NIU', 'name' => 'Niue']);
		Country::create(['iso_cod' => 'NOR', 'name' => 'Noruega']);
		Country::create(['iso_cod' => 'NCL', 'name' => 'Nueva Caledonia']);
		Country::create(['iso_cod' => 'NZL', 'name' => 'Nueva Zelanda']);
		Country::create(['iso_cod' => 'OMN', 'name' => 'Omán']);
		Country::create(['iso_cod' => 'NLD', 'name' => 'Países Bajos']);
		Country::create(['iso_cod' => 'PAK', 'name' => 'Pakistán']);
		Country::create(['iso_cod' => 'PLW', 'name' => 'Palau']);
		Country::create(['iso_cod' => 'PSE', 'name' => 'Palestina']);
		Country::create(['iso_cod' => 'PAN', 'name' => 'Panamá']);
		Country::create(['iso_cod' => 'PNG', 'name' => 'Papúa Nueva Guinea']);
		Country::create(['iso_cod' => 'PRY', 'name' => 'Paraguay']);
		Country::create(['iso_cod' => 'PER', 'name' => 'Perú']);
		Country::create(['iso_cod' => 'PYF', 'name' => 'Polinesia Francesa']);
		Country::create(['iso_cod' => 'POL', 'name' => 'Polonia']);
		Country::create(['iso_cod' => 'PRT', 'name' => 'Portugal']);
		Country::create(['iso_cod' => 'PRI', 'name' => 'Puerto Rico']);
		Country::create(['iso_cod' => 'QAT', 'name' => 'Qatar']);
		Country::create(['iso_cod' => 'GBR', 'name' => 'Reino Unido']);
		Country::create(['iso_cod' => 'COG', 'name' => 'República del Congo']);
		Country::create(['iso_cod' => 'CAF', 'name' => 'República Centroafricana']);
		Country::create(['iso_cod' => 'CZE', 'name' => 'República Checa']);
		Country::create(['iso_cod' => 'DOM', 'name' => 'República Dominicana']);
		Country::create(['iso_cod' => 'REU', 'name' => 'Reunión']);
		Country::create(['iso_cod' => 'RWA', 'name' => 'Ruanda']);
		Country::create(['iso_cod' => 'ROU', 'name' => 'Rumanía']);
		Country::create(['iso_cod' => 'RUS', 'name' => 'Rusia']);
		Country::create(['iso_cod' => 'ESH', 'name' => 'Sahara Occidental']);
		Country::create(['iso_cod' => 'WSM', 'name' => 'Samoa']);
		Country::create(['iso_cod' => 'ASM', 'name' => 'Samoa Americana']);
		Country::create(['iso_cod' => 'KNA', 'name' => 'San Cristóbal y Nieves']);
		Country::create(['iso_cod' => 'SMR', 'name' => 'San Marino']);
		Country::create(['iso_cod' => 'SPM', 'name' => 'San Pedro y Miquelón']);
		Country::create(['iso_cod' => 'VCT', 'name' => 'San Vicente y las Granadinas']);
		Country::create(['iso_cod' => 'SHN', 'name' => 'Santa Elena']);
		Country::create(['iso_cod' => 'LCA', 'name' => 'Santa Lucía']);
		Country::create(['iso_cod' => 'STP', 'name' => 'Santo Tomé y Príncipe']);
		Country::create(['iso_cod' => 'SEN', 'name' => 'Senegal']);
		Country::create(['iso_cod' => 'SRB', 'name' => 'Serbia']);
		Country::create(['iso_cod' => 'SYC', 'name' => 'Seychelles']);
		Country::create(['iso_cod' => 'SLE', 'name' => 'Sierra Leona']);
		Country::create(['iso_cod' => 'SGP', 'name' => 'Singapur']);
		Country::create(['iso_cod' => 'SYR', 'name' => 'Siria']);
		Country::create(['iso_cod' => 'SOM', 'name' => 'Somalia']);
		Country::create(['iso_cod' => 'LKA', 'name' => 'Sri lanka']);
		Country::create(['iso_cod' => 'ZAF', 'name' => 'Sudáfrica']);
		Country::create(['iso_cod' => 'SDN', 'name' => 'Sudán']);
		Country::create(['iso_cod' => 'SWE', 'name' => 'Suecia']);
		Country::create(['iso_cod' => 'CHE', 'name' => 'Suiza']);
		Country::create(['iso_cod' => 'SUR', 'name' => 'Surinám']);
		Country::create(['iso_cod' => 'SJM', 'name' => 'Svalbard y Jan Mayen']);
		Country::create(['iso_cod' => 'SWZ', 'name' => 'Swazilandia']);
		Country::create(['iso_cod' => 'TJK', 'name' => 'Tayikistán']);
		Country::create(['iso_cod' => 'TZA', 'name' => 'Tailandia']);
		Country::create(['iso_cod' => 'TWN', 'name' => 'Taiwán']);
		Country::create(['iso_cod' => 'TZA', 'name' => 'Tanzania']);
		Country::create(['iso_cod' => 'IOT', 'name' => 'Territorio Británico del Océano Índico']);
		Country::create(['iso_cod' => 'ATF', 'name' => 'Territorios Australes y Antárticas Franceses']);
		Country::create(['iso_cod' => 'TLS', 'name' => 'Timor Oriental']);
		Country::create(['iso_cod' => 'TGO', 'name' => 'Togo']);
		Country::create(['iso_cod' => 'TKL', 'name' => 'Tokelau']);
		Country::create(['iso_cod' => 'TON', 'name' => 'Tonga']);
		Country::create(['iso_cod' => 'TTO', 'name' => 'Trinidad y Tobago']);
		Country::create(['iso_cod' => 'TUN', 'name' => 'Tunez']);
		Country::create(['iso_cod' => 'TKM', 'name' => 'Turkmenistán']);
		Country::create(['iso_cod' => 'TUR', 'name' => 'Turquía']);
		Country::create(['iso_cod' => 'TUV', 'name' => 'Tuvalu']);
		Country::create(['iso_cod' => 'UKR', 'name' => 'Ucrania']);
		Country::create(['iso_cod' => 'UGA', 'name' => 'Uganda']);
		Country::create(['iso_cod' => 'URY', 'name' => 'Uruguay']);
		Country::create(['iso_cod' => 'UZB', 'name' => 'Uzbekistán']);
		Country::create(['iso_cod' => 'VUT', 'name' => 'Vanuatu']);
		Country::create(['iso_cod' => 'VEN', 'name' => 'Venezuela']);
		Country::create(['iso_cod' => 'VNM', 'name' => 'Vietnam']);
		Country::create(['iso_cod' => 'WLF', 'name' => 'Wallis y Futuna']);
		Country::create(['iso_cod' => 'YEM', 'name' => 'Yemen']);
		Country::create(['iso_cod' => 'DJI', 'name' => 'Yibuti']);
		Country::create(['iso_cod' => 'ZMB', 'name' => 'Zambia']);
		Country::create(['iso_cod' => 'ZWE', 'name' => 'Zimbabue']);
		*/
    }
}
